### ISSUE TITLE
links to colab notebooks in readme do not work

### ISSUE THREAD

**Issue by kaczmarj** [54yyyu/evoaug-tf_analysis#1]
When I try the link https://colab.research.google.com/drive/1sCYAL133F1PPbn7aGOxeQTFW-6fpLo4r?authuser=1#scrollTo=bcXlZ57uncra I get the following error:

![image](https://github.com/54yyyu/evoaug-tf_analysis/assets/17690870/812d7d8d-9fee-48d6-8c3b-20c27cf983b2)

similar error appears with the other two notebook links

**Comment by 54yyyu** [comment]
Just fixed it. Thank you for the reminder!
